name = "alicesaidhi/conch_language"
version = "0.3.0-rc.4"
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]