name = "alicesaidhi/conch_ast"
version = "0.2.1-rc.2"
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
types = { workspace = "alicesaidhi/conch_types", version = "^" }