name: release
on:
  release:
    types: [published]

permissions:
    contents: write

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install
        run: |
          pesde install

      - name: Build rbxm and release
        run: |
          cd pkgs/conch_standalone
          rojo build default.project.json -o standalone.rbxm
          gh release upload ${{github.event.release.tag_name}} standalone.rbxm